#!/usr/bin/env python3
from __future__ import annotations

import ast
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "cloud_instance"
OUTPUT = ROOT / "CODEMAP.md"

LAYER_NOTES = {
    "cloud_instance/cli.py": "Typer CLI entrypoint. Parses JSON options and dispatches command handlers.",
    "cloud_instance/commands/create.py": "Create/converge command: fetch current state, build delta, provision new instances, terminate surplus.",
    "cloud_instance/commands/delete.py": "Delete command: fetch and terminate all instances for a deployment.",
    "cloud_instance/commands/gather.py": "Gather command: return current instances for a deployment.",
    "cloud_instance/commands/slated.py": "Slated command: show instances that would be deleted by convergence.",
    "cloud_instance/commands/modify.py": "Modify command: change instance type/CPU size for selected instances.",
    "cloud_instance/commands/resize.py": "Resize command: resize disks for selected instances.",
    "cloud_instance/core/build.py": "Reconciliation planner. Compares desired deployment groups with fetched instances and creates provider work items.",
    "cloud_instance/core/fetch.py": "Provider-neutral fetch coordinator.",
    "cloud_instance/core/provision.py": "Provider-neutral provisioning coordinator.",
    "cloud_instance/core/terminate.py": "Provider-neutral termination coordinator.",
    "cloud_instance/models.py": "Typed deployment schema and shared enums.",
    "cloud_instance/providers/aws.py": "AWS lifecycle implementation: fetch, parse, provision, and terminate.",
    "cloud_instance/providers/azure.py": "Azure lifecycle implementation: parse, provision, and terminate.",
    "cloud_instance/providers/gcp.py": "GCP lifecycle implementation: fetch, parse, provision, and terminate.",
}

AGENT_RULES = [
    "Keep CLI argument parsing in `cloud_instance/cli.py`; put command behavior in `cloud_instance/commands/`.",
    "Keep deployment schema changes in `cloud_instance/models.py`.",
    "Keep reconciliation/provider-neutral planning in `cloud_instance/core/build.py`.",
    "Keep provider-specific create/fetch/parse/delete behavior in `cloud_instance/providers/`.",
    "Preserve the common instance dict shape returned by parsers unless every caller is updated together.",
    "Deployment models may validate and normalize input, but provider code currently consumes plain dicts.",
]


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def public_defs(path: Path) -> tuple[list[str], list[str]]:
    tree = ast.parse(path.read_text(), filename=str(path))
    classes: list[str] = []
    functions: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            classes.append(node.name)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            functions.append(node.name)

    return classes, functions


def module_rows() -> list[str]:
    rows = []
    for path in sorted(PACKAGE.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        name = rel(path)
        classes, functions = public_defs(path)
        symbols = []
        if classes:
            symbols.append("classes: " + ", ".join(classes))
        if functions:
            symbols.append("functions: " + ", ".join(functions))

        note = LAYER_NOTES.get(name, "")
        detail = "; ".join(symbols) if symbols else "no public classes/functions"
        if note:
            detail = f"{note} {detail}"

        rows.append(f"| `{name}` | {detail} |")
    return rows


def render() -> str:
    lines = [
        "# Code Map",
        "",
        "<!-- Generated by tools/generate_codemap.py. Do not edit by hand. -->",
        "",
        "This file is a compact guide for humans and LLM agents working in this repository.",
        "Regenerate it after structural code changes with:",
        "",
        "```bash",
        "python3 tools/generate_codemap.py",
        "```",
        "",
        "## Golden Flows",
        "",
        "- Create/converge: `cli.py` -> `commands/create.py` -> `core/fetch.py` -> `providers/*` -> `core/build.py` -> `core/provision.py` -> `providers/*` -> optional `core/terminate.py`",
        "- Delete: `cli.py` -> `commands/delete.py` -> `core/fetch.py` -> `providers/*` -> `core/terminate.py` -> `providers/*`",
        "- Query: `cli.py` -> `commands/gather.py` -> `core/fetch.py` -> `providers/*`",
        "- Slated-for-delete preview: `cli.py` -> `commands/slated.py` -> `core/fetch.py` -> `providers/*` -> `core/build.py`",
        "- Modify/resize: `cli.py` -> `commands/modify.py` or `commands/resize.py` -> provider APIs",
        "",
        "## Agent Rules",
        "",
    ]

    lines.extend(f"- {rule}" for rule in AGENT_RULES)
    lines.extend(
        [
            "",
            "## Modules",
            "",
            "| File | Purpose / Public Surface |",
            "| --- | --- |",
            *module_rows(),
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    content = render()
    if sys.argv[1:] == ["--check"]:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print("CODEMAP.md is out of date. Run: python3 tools/generate_codemap.py")
            raise SystemExit(1)
        return

    if sys.argv[1:]:
        print("Usage: python3 tools/generate_codemap.py [--check]")
        raise SystemExit(2)

    OUTPUT.write_text(content)


if __name__ == "__main__":
    main()
